apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb-deployment
  labels:
    app: helloweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloweb
  template:
    metadata:
      labels:
        app: helloweb
    spec:
      containers:
      - name: helloweb
        image: 527720397058.dkr.ecr.us-east-2.amazonaws.com/argocd:7eb249880c0c38047b7614b90b9fb05e205a7cb1 527720397058.dkr.ecr.us-east-2.amazonaws.com/argocd:40ccda4cd816dc0f2ff57a977974dcb6baf884bc 527720397058.dkr.ecr.us-east-2.amazonaws.com/argocd:2e1208fac1ff4e665dfaa476ab8574328657e87a 527720397058.dkr.ecr.us-east-2.amazonaws.com/argocd:65194fc57305b7a64d6fcd0c9b4335e2eeb555cb
        ports:
        - containerPort: 80
