apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb-deployment
  labels:
    app: helloweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloweb
  template:
    metadata:
      labels:
        app: helloweb
    spec:
      containers:
      - name: helloweb
        image: 373474467195.dkr.ecr.us-east-2.amazonaws.com/argocd:cb455124ff4704df0aa2417b8baabf9dd0776a08
        ports:
        - containerPort: 80
