apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb-deployment
  labels:
    app: helloweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloweb
  template:
    metadata:
      labels:
        app: helloweb
    spec:
      containers:
      - name: helloweb
        image: 527720397058.dkr.ecr.us-east-2.amazonaws.com/argocd:e80732a3a71e97a5318a0252822027e9fc5c327f
        ports:
        - containerPort: 80
